name: Deploy Cloudfolio

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::304707804854:role/cloudfolio-github-actions
          aws-region: eu-west-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.5"

      - name: Deploy
        run: infra/cloudfolio/deploy.sh
